import { getPlatformConfig, type Platform } from './platforms.js';

/**
 * Components that are deprecated in the product but not marked as such in the
 * API reference the MCP is built from (the shipped code carries no [Obsolete]
 * attribute or deprecation tag). Every symbol listed here is dropped from
 * the API index, and any tool asked about one answers with a deprecation
 * notice instead of documentation.
 *
 * Temporary: remove an entry once the upstream API reference flags it.
 */
export interface Deprecation {
  platform: Platform;
  /** The component the notice is about, e.g. "IgbDataGrid". */
  component: string;
  /** What to use instead, e.g. "IgbGrid". */
  replacement: string;
  /** Framework-specific pointer to the replacement, appended to the notice. */
  guidance: string;
  /** Every API symbol to hide: the component plus every type only it uses. */
  symbols: readonly string[];
}

export const DEPRECATIONS: readonly Deprecation[] = [
  {
    platform: 'blazor',
    component: 'IgbDataGrid',
    replacement: 'IgbGrid',
    guidance:
      'Declare its columns with `IgbColumn`, not `IgbTextColumn`, `IgbNumericColumn` or the other ' +
      'IgbDataGrid column types. Look it up with get_api_reference (platform "blazor", component ' +
      '"IgbGrid") or search_docs (framework "blazor", e.g. "grid editing").',
    // Verified against IgniteUI.Blazor 25.1.19: nothing outside this list references these types.
    symbols: [
      // The component, its helpers and modules.
      'IgbDataGrid',
      'IgbDataGridCellEventArgs',
      'IgbDataGridColumn',
      'IgbDataGridComparisonOperatorSelector',
      'IgbDataGridExpansionIndicator',
      'IgbDataGridFilterDialog',
      'IgbDataGridPager',
      'IgbDataGridSortIndicator',
      'IgbDataGridSummaryResult',
      'IgbDataGridToolbar',
      'IgbDataGridAllColumnsModule',
      'IgbDataGridCoreModule',
      'IgbDataGridLocaleEnModule',
      'IgbDataGridModule',
      'IgbDataGridPagerModule',
      'IgbDataGridToolbarModule',
      // Column types — all derive from IgbDataGridColumn and only work inside IgbDataGrid.
      'IgbComboBoxColumn',
      'IgbDateTimeColumn',
      'IgbImageColumn',
      'IgbNumericColumn',
      'IgbTemplateColumn',
      'IgbTextColumn',
      'IgbComboBoxColumnModule',
      'IgbDateTimeColumnModule',
      'IgbImageColumnModule',
      'IgbNumericColumnModule',
      'IgbTemplateColumnModule',
      'IgbTextColumnModule',
      // Enums only IgbDataGrid settings use, e.g. IgbDataGrid.EditModeClickAction.
      'CellDataLoadedAnimationMode',
      'CellSelectionAnimationMode',
      'ColumnExchangingAnimationMode',
      'ColumnHidingAnimationMode',
      'ColumnMovingAnimationMode',
      'ColumnMovingMode',
      'ColumnPropertyUpdatingAnimationMode',
      'ColumnResizingAnimationMode',
      'ColumnResizingMode',
      'ColumnShowingAnimationMode',
      'DataGridSelectionMode',
      'EditModeClickAction',
      'EditModeType',
      'EnterKeyBehaviorAfterEdit',
      'EnterKeyBehaviors',
      'FilterComparisonType',
      'FilterLogicalOperator',
      'FilterUIType',
      'GridActivationMode',
      'GridSelectionBehavior',
      'GroupHeaderDisplayMode',
      'HeaderClickAction',
      'MergedCellEvaluationCriteria',
      'MergedCellMode',
      'RowHoverAnimationMode',
      'RowSelectionAnimationMode',
      'SummaryScope',
      // Event args and settings classes only the old grid's components use.
      'IgbColumnHiddenChangedEventArgs',
      'IgbColumnPinnedChangedEventArgs',
      'IgbFilterDialogRenderCompletedEventArgs',
      'IgbFormatCellEventArgs',
      'IgbGridActiveCellChangedEventArgs',
      'IgbGridAnimationSettings',
      'IgbGridCellEditEndedEventArgs',
      'IgbGridCellEditStartedEventArgs',
      'IgbGridCellValueChangingEventArgs',
      'IgbGridColumnAnimationSettings',
      'IgbGridColumnWidthChangedEventArgs',
      'IgbGridColumnsAutoGeneratedEventArgs',
      'IgbGridColumnsChangedEventArgs',
      'IgbGridDataCommittedEventArgs',
      'IgbGridDataCommittingEventArgs',
      'IgbGridFilterDialogFilterChangeEventArgs',
      'IgbGridFilterDialogOpeningEventArgs',
      'IgbGridFilterExpressionsEventArgs',
      'IgbGridGroupDescriptionsChangedEventArgs',
      'IgbGridRowEditEndedEventArgs',
      'IgbGridRowEditStartedEventArgs',
      'IgbGridSelectedCellRangesChangedEventArgs',
      'IgbGridSelectedCellsChangedEventArgs',
      'IgbGridSelectedItemsChangedEventArgs',
      'IgbGridSelectedKeysChangedEventArgs',
      'IgbGridSelectionChangedEventArgs',
      'IgbGridSizeChangedEventArgs',
      'IgbGridSortDescriptionsChangedEventArgs',
      'IgbGridSummaryDescriptionsChangedEventArgs',
      'IgbOperatorSelectorClosingEventArgs',
      'IgbOperatorSelectorOpeningEventArgs',
      'IgbOperatorSelectorValueChangedEventArgs',
      'IgbPageChangedEventArgs',
      'IgbResponsiveStatesCollection',
      'IgbSortIndicatorRenderCompletedEventArgs',
      'IgbTemplateCellUpdatingEventArgs',
    ],
  },
];

// Without a known platform only prefixed names are unambiguous: plain names such as
// DataGridSelectionMode also exist in the React and Web Components data-grid packages.
const PLATFORM_PREFIXES: Record<Platform, string> = {
  angular: 'Igx',
  react: 'Igr',
  webcomponents: 'Igc',
  blazor: 'Igb',
};

/** Generic parameters always trail the name in C#: "IgbCombo<T>" → "igbcombo". */
function normalize(symbol: string): string {
  return symbol.split('<')[0].trim().toLowerCase();
}

/** The symbols that identify `d` for a lookup on `platform`. */
function symbolsFor(d: Deprecation, platform: Platform | undefined): readonly string[] {
  if (platform) return d.platform === platform ? d.symbols : [];
  return d.symbols.filter(s => s.startsWith(PLATFORM_PREFIXES[d.platform]));
}

/** The deprecation covering `symbol` (case-insensitive, generics ignored), if any. */
export function findDeprecation(platform: Platform | undefined, symbol: string): Deprecation | undefined {
  const name = normalize(symbol);
  return DEPRECATIONS.find(d => symbolsFor(d, platform).some(s => s.toLowerCase() === name));
}

/** Deprecations whose symbols are mentioned anywhere in `texts`. */
export function findDeprecationsInText(platform: Platform | undefined, ...texts: string[]): Deprecation[] {
  return DEPRECATIONS.filter(d => {
    const symbols = symbolsFor(d, platform);
    if (symbols.length === 0) return false;
    const pattern = new RegExp(`\\b(?:${symbols.join('|')})\\b`, 'i');
    return texts.some(t => pattern.test(t));
  });
}

// Models fall back on what they learned in training, so the rule also has to
// rule out offering the component as a "legacy" alternative.
const NO_SUGGESTION_RULE =
  'not even as a legacy option or an alternative, and not for settings that only exist on it. ' +
  "If the user's existing code already uses it, recommend migrating.";

/** The notice for `d`, naming which of the `requested` symbols belong to it. */
export function formatDeprecationNotice(d: Deprecation, requested: readonly string[] = []): string {
  const parts = requested
    .map(r => d.symbols.find(s => s.toLowerCase() === normalize(r)))
    .filter((s): s is string => s !== undefined && s !== d.component);
  const partOf = parts.length ? `Part of its API: ${parts.map(s => `\`${s}\``).join(', ')}. ` : '';
  return (
    `⚠ DEPRECATED: \`${d.component}\` (${getPlatformConfig(d.platform).displayName}) is deprecated and has been ` +
    `replaced by \`${d.replacement}\`. ${partOf}It receives no new features and bug fixes are deprioritized. ` +
    `Do not suggest \`${d.component}\` or any type that belongs to it — ` +
    `${NO_SUGGESTION_RULE} Use \`${d.replacement}\` instead. ${d.guidance}`
  );
}

/** The deprecations as a server-instructions paragraph, so clients know before any tool call. */
export function formatDeprecationInstructions(): string {
  if (DEPRECATIONS.length === 0) return '';
  const items = DEPRECATIONS.map(
    d => `${d.component} (${getPlatformConfig(d.platform).displayName}) → use ${d.replacement}`
  );
  return `DEPRECATED COMPONENTS: never suggest ${items.join('; ')} — ${NO_SUGGESTION_RULE}`;
}

/** Prepends to `body` a notice for every deprecation mentioned in `scanned`. */
export function withDeprecationNotices(platform: Platform | undefined, body: string, scanned: string[]): string {
  const found = findDeprecationsInText(platform, ...scanned);
  if (found.length === 0) return body;
  return `${found.map(d => formatDeprecationNotice(d)).join('\n\n')}\n\n${body}`;
}
