name: Deploy GitHub Pages

on:
  push:
    branches: [ <%=yamlDefaultBranch%> ]
  pull_request:
    branches: [ <%=yamlDefaultBranch%> ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - name: Set project name
      run: echo "PROJECT_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV
    - name: Build project with dynamic base-href
      run: npm run build -- --base-href "/${{ github.event.repository.name }}/"
    - name: Update Resource Paths
      run: find ./dist/${{ env.PROJECT_NAME }} -type f -name '*main*.js' -exec sed -i -e "s|/assets|/${{ github.event.repository.name }}/assets|g" -e "s|url('/assets|url('/${{ github.event.repository.name }}/assets|g" {} +
    - name: Upload build artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist/${{ env.PROJECT_NAME }}
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
